GET http://localhost:8000/products/ HTTP/1.1

###

POST http://localhost:8000/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzMjU2NTQ3LCJpYXQiOjE3NDMyNTYyNDcsImp0aSI6ImZmODRmY2RkZTAyODQwOGU4OTYyODgwMDNhNzg2NWVmIiwidXNlcl9pZCI6Mn0.oHnH8GR2dk81fKw18N3Q7tBSBecuNNlsK1cbupoGomU

{
    "name": "Television 2",
    "price": 301.00,
    "stock": 15,
    "description": "Amazing New TV 2"
}

###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "lp_12345678"
}

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0MzM0MzIyNSwiaWF0IjoxNzQzMjU2ODI1LCJqdGkiOiIzYzlkODk4MWQ5NTQ0MWY1YmRlMjNlYjAzMWU3ZGExMyIsInVzZXJfaWQiOjJ9.eajARTV8cUDGt3VaWPThcVBysIkqoTdS_JhZOIohy5A"
}

###
GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzMjU2NTQ3LCJpYXQiOjE3NDMyNTYyNDcsImp0aSI6ImZmODRmY2RkZTAyODQwOGU4OTYyODgwMDNhNzg2NWVmIiwidXNlcl9pZCI6Mn0.oHnH8GR2dk81fKw18N3Q7tBSBecuNNlsK1cbupoGomU

###
GET http://localhost:8000/products/15/ HTTP/1.1

###
DELETE http://localhost:8000/products/14/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzMzAyNTIyLCJpYXQiOjE3NDMyNTkzMjIsImp0aSI6IjI4ZWY0NmVkZTU3MzQxN2FiMWYxYTYwMDRmZTBhZTE5IiwidXNlcl9pZCI6MX0.yIFot3Ziit6G6ZpL8hK9XDUuNDyC5tvTIkQMdqj46tg

###
PUT http://localhost:8000/products/14/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzMzAwNTgwLCJpYXQiOjE3NDMyNTczODAsImp0aSI6IjNmMGY0NGQ5NDk2ODQzZWI5MGJmMmE4N2FjMDgxZWFiIiwidXNlcl9pZCI6Mn0.95gQKi30Ch3C0jfLQkv4sUkU-3RnmBp6nykvlG0P_QI

{
    "description": "Amazing New TV 4",
    "name": "Television 4",
    "price": "403.00",
    "stock": 40
}
